"""Tasks

Revision ID: 508a3afd1d3c
Revises: eba0ff7354ff
Create Date: 2025-03-08 00:53:09.991603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508a3afd1d3c'
down_revision: Union[str, None] = 'eba0ff7354ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('channel_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('invite_link', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('chat_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('bot_username', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('bot_token', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('giphy_url', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('tasks_link_key', 'tasks', type_='unique')
    op.drop_constraint('tasks_tg_id_key', 'tasks', type_='unique')
    op.create_unique_constraint(None, 'tasks', ['order'])
    op.drop_column('tasks', 'tg_id')
    op.drop_column('tasks', 'link')
    op.add_column('withdrawl_requests', sa.Column('dd', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawl_requests', 'dd')
    op.add_column('tasks', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('tg_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='unique')
    op.create_unique_constraint('tasks_tg_id_key', 'tasks', ['tg_id'])
    op.create_unique_constraint('tasks_link_key', 'tasks', ['link'])
    op.alter_column('tasks', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'giphy_url')
    op.drop_column('tasks', 'bot_token')
    op.drop_column('tasks', 'bot_username')
    op.drop_column('tasks', 'chat_id')
    op.drop_column('tasks', 'invite_link')
    op.drop_column('tasks', 'channel_id')
    op.drop_column('tasks', 'title')
    op.drop_column('tasks', 'order')
    # ### end Alembic commands ###
