"""Tasks

Revision ID: 61252a6cb3ad
Revises: 508a3afd1d3c
Create Date: 2025-03-08 00:55:12.132715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61252a6cb3ad'
down_revision: Union[str, None] = '508a3afd1d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_task_data_user_id_fkey', 'user_task_data', type_='foreignkey')
    op.create_foreign_key(None, 'user_task_data', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_task_data', type_='foreignkey')
    op.create_foreign_key('user_task_data_user_id_fkey', 'user_task_data', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
