"""fix_withdraw_requests_pk

Revision ID: 9af92976978e
Revises: c9dd795eddd4
Create Date: 2025-03-07 16:16:12.202827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af92976978e'
down_revision: Union[str, None] = 'c9dd795eddd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
