"""fix_withdraw_requests_pk

Revision ID: 9d959fd029cc
Revises: 26ae3c411f36
Create Date: 2025-03-10 20:52:12.553800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d959fd029cc'
down_revision: Union[str, None] = '26ae3c411f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
