"""Withdraw

Revision ID: c9dd795eddd4
Revises: d3c22307e516
Create Date: 2025-03-07 11:18:16.471188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9dd795eddd4'
down_revision: Union[str, None] = 'd3c22307e516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawl_requests', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('withdrawl_requests', sa.Column('gift_type', sa.String(length=50), nullable=False))
    op.add_column('withdrawl_requests', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('withdrawl_requests', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawl_requests', 'created_at')
    op.drop_column('withdrawl_requests', 'status')
    op.drop_column('withdrawl_requests', 'gift_type')
    op.drop_column('withdrawl_requests', 'id')
    # ### end Alembic commands ###
