"""add_promo_activation_system

Revision ID: d3c22307e516
Revises: 019ca8a77c08
Create Date: 2025-03-05 21:38:26.431395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c22307e516'
down_revision: Union[str, None] = '019ca8a77c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_promocodes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('promocode_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['promocode_id'], ['promocodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'promocode_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_promocodes')
    # ### end Alembic commands ###
