"""fix_withdraw_requests_pk

Revision ID: f4ee41e6a209
Revises: aa7081f7ab02
Create Date: 2025-03-10 18:54:19.104712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ee41e6a209'
down_revision: Union[str, None] = 'aa7081f7ab02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
