"""Tasks

Revision ID: fca4df773beb
Revises: 61252a6cb3ad
Create Date: 2025-03-08 00:58:28.320962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca4df773beb'
down_revision: Union[str, None] = '61252a6cb3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_task_data', sa.Column('task_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'user_task_data', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_task_data', type_='foreignkey')
    op.drop_column('user_task_data', 'task_id')
    # ### end Alembic commands ###
